remote_theme: Zelirian/github-pages-themes-hacker@gh-pages
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-hacker
title: Zelirian
# url: http://google.com
# baseurl: https://www.google.it/imghp?hl=it&ogbl
relative_url: https://github.com/Zelirian
# permalink: github.com/Zelirian
description: |
  ğŸ’» Senior Developer | â™¨ï¸ Back-End Specialist | â˜ï¸ DevOps | ğŸ“Š Trading & Quant Dev | ğŸ§  Engineering-Minded<br />
  To study and improve are my favorite ways to make myself better for the next challenge<br />
  "Luck is what happens when preparation meets opportunity"<br />
  "It's a Long Way to the Top (If You Wanna Rock 'N' Roll)"
github:
 # repository_name: https://marketingplatform.google.com/about/
 repository_url: https://github.com/Zelirian
 # profile_url: https://github.com/Zelirian
 is_project_page: true
# defaults:
# - downloads: hide
